// Structured data for AEO (Answer Engine Optimization)
export const qrGeneratorStructuredData = {
  '@context': 'https://schema.org',
  '@type': 'SoftwareApplication',
  name: 'QR Code Generator',
  applicationCategory: 'DeveloperApplication',
  operatingSystem: 'Web',
  offers: {
    '@type': 'Offer',
    price: '0',
    priceCurrency: 'USD',
  },
  aggregateRating: {
    '@type': 'AggregateRating',
    ratingValue: '4.9',
    ratingCount: '1020',
  },
  description: 'Free online QR code generator. Create QR codes for URLs, text, phone numbers, email, SMS, WiFi, and vCards instantly. Customize size, error correction level, and download as PNG/SVG. High-quality QR codes with no expiration.',
  featureList: [
    'URL QR code generation',
    'Text QR code generation',
    'Phone number QR codes',
    'Email QR codes',
    'SMS QR codes',
    'WiFi QR codes (SSID & Password)',
    'vCard QR codes (contact info)',
    'Customizable size',
    'Error correction levels (L, M, Q, H)',
    'PNG and SVG download',
    'High resolution output',
    'No expiration',
    'No login required',
    'Privacy-first (client-side generation)',
  ],
  screenshot: 'https://devtools-hub-app.vercel.app/screenshots/qr-generator.png',
}

// FAQ for AEO
export const qrGeneratorFAQ = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    {
      '@type': 'Question',
      name: 'What is a QR code?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'A QR code (Quick Response code) is a two-dimensional barcode that can store various types of data like URLs, text, contact information, WiFi credentials, etc. Users can scan QR codes with smartphones to quickly access the encoded information without typing.',
      },
    },
    {
      '@type': 'Question',
      name: 'How do I create a QR code for my website?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'To create a URL QR code: 1) Select "URL" type, 2) Enter your website URL (e.g., https://example.com), 3) Click Generate, 4) Download the QR code as PNG or SVG. The QR code will redirect users to your website when scanned.',
      },
    },
    {
      '@type': 'Question',
      name: 'What error correction level should I use?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Error correction allows QR codes to be readable even if partially damaged. Levels: L (7% recovery, smallest), M (15%, recommended), Q (25%), H (30%, most durable). Use M for general purposes, H for printed materials that may get damaged, and L for digital-only QR codes to minimize size.',
      },
    },
    {
      '@type': 'Question',
      name: 'Do QR codes expire?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'No, QR codes generated by this tool never expire. The data is embedded directly in the QR code image itself, not stored on a server. As long as you have the QR code image, it will work forever. This is true for all static QR codes (URL, text, contact, etc.).',
      },
    },
    {
      '@type': 'Question',
      name: 'Can I create WiFi QR codes?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Yes! Select "WiFi" type and enter your network name (SSID), password, and security type (WPA/WEP/None). When users scan the QR code, their device will automatically prompt to connect to your WiFi network without manual password entry. Perfect for guest WiFi access.',
      },
    },
  ],
}

// HowTo for AEO
export const qrGeneratorHowTo = {
  '@context': 'https://schema.org',
  '@type': 'HowTo',
  name: 'How to Create QR Codes Online',
  description: 'Step-by-step guide to generate QR codes for URLs, text, WiFi, contacts, and more',
  step: [
    {
      '@type': 'HowToStep',
      name: 'Select QR Code Type',
      text: 'Choose what type of QR code you want to create: URL (website links), Text (plain text), Phone (tel: links), Email (mailto: links), SMS, WiFi (network credentials), or vCard (contact information).',
      image: 'https://devtools-hub-app.vercel.app/screenshots/qr-step1.png',
    },
    {
      '@type': 'HowToStep',
      name: 'Enter Data',
      text: 'Fill in the required information for your selected type. For URLs, enter the web address. For WiFi, enter SSID and password. For vCards, enter name, phone, email, etc. The tool validates your input.',
      image: 'https://devtools-hub-app.vercel.app/screenshots/qr-step2.png',
    },
    {
      '@type': 'HowToStep',
      name: 'Customize Settings',
      text: 'Adjust QR code size (100-1000px) and error correction level (L/M/Q/H). Higher error correction makes QR codes more durable but larger. Medium (M) is recommended for most uses.',
      image: 'https://devtools-hub-app.vercel.app/screenshots/qr-step3.png',
    },
    {
      '@type': 'HowToStep',
      name: 'Download QR Code',
      text: 'Click Generate to create your QR code. Preview it, then download as PNG (raster) or SVG (vector). PNG is good for web/screen use, SVG is best for printing and scaling without quality loss.',
      image: 'https://devtools-hub-app.vercel.app/screenshots/qr-step4.png',
    },
  ],
}
